import { Inter, Archivo, Archivo_Narrow } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import Image from "next/image";
import runBG from "@/../public/runBG.jpg";
import AnimateTitle from "./components/AnimateTitle";
import { revalidatePath } from "next/cache";

const inter = Inter({ subsets: ["latin"] });
export const main_font = Archivo_Narrow({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  revalidatePath("/");

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="absolute">
          <Nav />
          <Image src={runBG} alt="background image" className="bg-contain" />
          <AnimateTitle className="relative top-4 left-4" />
          {children}
        </div>
      </body>
    </html>
  );
}

// className="relative h-screen"
